[project]
name = "ragas"
dependencies = [
    "numpy",
    "transformers",
    "sentence-transformers",
    "datasets",
    "tiktoken",
    "langchain>=0.0.288",
    "openai",
    "pydantic<2.0",
    "pysbd>=0.3.4",
]
dynamic = ["version", "readme"]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinxawesome-theme@git+https://github.com/jjmachan/sphinxawesome-theme.git@fix/docsearch",
    "myst-parser[linkify]",
    "sphinx_design",
    "astroid<3",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/plain"}

[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/ragas/_version.py"
