[project]
name = "belar"
dependencies = [
    "Levenshtein",
    "rouge-score",
    "numpy",
    "transformers",
    "sentence-transformers",
    "nltk",
    "datasets",
]
dynamic = ["version", "readme"]

[project.optional-dependencies]
test = [
    # "pytest-cov",
    "pytest",
    "rich",
]

dev = [
    "ruff",
    "isort",
    "black[jupyter]",
    "pyright",
]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/plain"}

[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
write_to = "belar/_version.py"
